package com.sfl.browser.clustering;

/**
 * Represents a grouped set of notifications ready to be delivered
 * Groups similar items (same category/name/timing) into single notification
 */
public class NotificationGroup {
    public String category;              // "crops", "fruits", "animals", etc.
    public String name;                  // "Beetroot", "Apple", "Chicken", etc.
    public int quantity;                 // How many of this item are ready
    public long earliestReadyTime;       // Milliseconds - when first item will be ready
    public String groupId;               // Unique ID for tracking already-notified (generated by clusterer)
    public String details;               // Optional details for complex notifications (e.g., cooking items list)
    
    public NotificationGroup() {
    }
    
    public NotificationGroup(String category, String name, int quantity, long earliestReadyTime) {
        this.category = category;
        this.name = name;
        this.quantity = quantity;
        this.earliestReadyTime = earliestReadyTime;
    }
    
    @Override
    public String toString() {
        return String.format("%s: %d %s @ %d", category, quantity, name, earliestReadyTime);
    }
}
